# Proces sprawdzania danych

In [8]:
import os

os.getcwd()

'/Users/michal/Badanie-Kataster'

In [13]:
# Wczytanie danych i ustalenie rodzajów zmiennych
import pandas as pd
import numpy as np
data = pd.read_csv(r"dane/warszawa_lokale.csv")
data['creation_date'] = pd.to_datetime(data['creation_date'])
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 229727 entries, 0 to 229726
Data columns (total 17 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   name             229727 non-null  str
 1   latitude         229727 non-null  float64
 2   longitude        229727 non-null  float64
 3   city             229727 non-null  str
 4   street           229727 non-null  str
 5   name.1           229727 non-null  str
 6   floor            227215 non-null  float64
 7   rooms            229727 non-null  int64
 8   size             229727 non-null  float64
 9   amount           229727 non-null  float64
 10  buyerType        229727 non-null  str
 11  sellerType       229727 non-null  str
 12  transactionType  229727 non-null  str
 13  marketType       229727 non-null  str
 14  participation    178809 non-null  str
 15  creation_date    229727 non-null  datetime64[us]
 16  classification   229727 non-null  str
dtypes: datetime64[us](1), float64(5), int64(1), str(10)
memory usage: 29.8 MB

## Participation

bierzemy pod uwagę tylko transakcje zakupu pełnej nieruchomości

In [38]:
data = data[data['participation'] == "1/1"]
data.shape

(176953, 17)

## Name 

Do wyrzucenia, street jest taki sam

In [39]:
print(data[data['street'] != data['name']])

data = data.drop("name",axis=1)

Empty DataFrame
Columns: [name, latitude, longitude, city, street, name.1, floor, rooms, size, amount, buyerType, sellerType, transactionType, marketType, participation, creation_date, classification]
Index: []

## Lattitude i Longitude

Do zbadania czy zgadzają się z granicami warszawy oraz z doborem losowym adresów

## City

do wyrzucenia

In [40]:
data = data.drop("city",axis=1)

## Street

zostaje

In [41]:
data['street']

0         Ulica Ppłk. Macieja Kalenkiewicza „kotwicza” 10
3                             Ulica Adolfa Pawińskiego 14
4                             Ulica Adolfa Pawińskiego 14
5                             Ulica Adolfa Pawińskiego 14
6                             Ulica Adolfa Pawińskiego 14
                               ...
229722                            Ulica Oskara Kolberga 2
229723                          Ulica Franciszka Raszei 6
229724                Ulica Bolesława Podczaszyńskiego 27
229725                                  Ulica Genewska 36
229726                                Ulica Wąski Dunaj 3
Name: street, Length: 176953, dtype: str

## name.1

mistyczna, wstępnie do wyrzucenia

In [42]:
data = data.drop('name.1',axis = 1)

## floor

1956 usunięcia puste
sprawdzenie poprawności danych

Najwyższa wartość zgadza się z wiedzą dot. złotej 44

bardzo mało nieruchomości na piętrach poniżej zero, można usunąć dla zasady...

In [50]:
print(data['floor'].describe())

print(f'brakuje {data.shape[0] - data[data['floor'].notna()].shape[0]} rekordów')

data = data[data['floor'].notna()]

count    174997.000000
mean          4.000971
std           2.925879
min          -1.000000
25%           2.000000
50%           3.000000
75%           5.000000
max          52.000000
Name: floor, dtype: float64
brakuje 1956 rekordów

In [44]:
data[(data['floor'] < 0)]

,latitude,longitude,street,floor,rooms,size,amount,buyerType,sellerType,transactionType,marketType,participation,creation_date,classification
6770,52.227569,20.887444,Ulica Szeligowska 32,-1.0,3,57.01,360000.0,osobaFizyczna,osobaPrawna,wolnyRynek,pierwotny,1/1,2017-06-12,transakcja
41850,52.205639,21.013258,Ulica Ludwika Narbutta 37,-1.0,4,72.12,800000.0,osobaPrawna,osobaFizyczna,wolnyRynek,wtorny,1/1,2023-04-06,transakcja
52503,52.191888,20.956138,Ulica Zbąszyńska 8,-1.0,3,75.10,503170.0,osobaFizyczna,osobaPrawna,wolnyRynek,pierwotny,1/1,2019-03-01,transakcja
88257,52.235955,20.991811,Ulica Waliców 17,-1.0,3,62.31,461020.0,osobaFizyczna,osobaFizyczna,wolnyRynek,pierwotny,1/1,2017-06-30,transakcja
96955,52.202132,21.030030,Ulica Padewska 19,-1.0,2,25.70,250000.0,osobaFizyczna,osobaFizyczna,wolnyRynek,wtorny,1/1,2018-08-08,transakcja
96956,52.202132,21.030030,Ulica Padewska 19,-1.0,2,25.70,435000.0,osobaFizyczna,osobaFizyczna,wolnyRynek,wtorny,1/1,2025-03-13,transakcja
104164,52.176285,21.037907,Aleja Wilanowska 287,-1.0,9,213.00,30000.0,osobaFizyczna,osobaFizyczna,wolnyRynek,wtorny,1/1,2017-12-28,anomalia_down
104165,52.176285,21.037907,Aleja Wilanowska 287,-1.0,9,213.00,1480000.0,osobaFizyczna,osobaFizyczna,wolnyRynek,wtorny,1/1,2019-03-15,transakcja
152700,52.205786,20.933441,Ulica Naukowa 30,-1.0,2,47.42,409000.0,osobaFizyczna,osobaFizyczna,wolnyRynek,wtorny,1/1,2023-10-16,transakcja
189477,52.195211,20.954468,Ulica Hejnałowa 11C,-1.0,3,39.03,380000.0,osobaFizyczna,osobaFizyczna,wolnyRynek,wtorny,1/1,2023-09-04,transakcja
212682,52.195263,20.954419,Ulica Hejnałowa 11B,-1.0,1,33.66,315000.0,osobaFizyczna,osobaFizyczna,wolnyRynek,wtorny,1/1,2023-01-25,transakcja
229595,52.209637,20.906142,Ulica Promienista 8,-1.0,1,21.40,255000.0,osobaFizyczna,osobaPrawna,wolnyRynek,pierwotny,1/1,2023-03-21,transakcja

## rooms

zbadać na czym polegają rooms = 0

In [51]:
data[data['rooms'] == 0]

,latitude,longitude,street,floor,rooms,size,amount,buyerType,sellerType,transactionType,marketType,participation,creation_date,classification
832,52.237125,20.925595,Ulica Górczewska 181,6.0,0,54.54,750000.0,osobaFizyczna,osobaFizyczna,wolnyRynek,wtorny,1/1,2023-06-19,transakcja
855,52.237125,20.925595,Ulica Górczewska 181,5.0,0,66.30,1080000.0,osobaFizyczna,osobaFizyczna,wolnyRynek,wtorny,1/1,2025-06-18,transakcja
1111,52.234699,20.993830,Ulica Grzybowska 39,14.0,0,48.00,770000.0,osobaPrawna,osobaFizyczna,wolnyRynek,wtorny,1/1,2024-04-24,transakcja
1437,52.285585,20.926886,Ulica Lekka 3,2.0,0,47.83,618000.0,osobaFizyczna,osobaFizyczna,wolnyRynek,wtorny,1/1,2022-11-24,transakcja
1684,52.170868,20.995772,Ulica Obrzeżna 1A,6.0,0,48.98,800000.0,osobaFizyczna,osobaFizyczna,wolnyRynek,wtorny,1/1,2023-04-26,transakcja
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
229443,52.286714,21.168911,Ulica Pastuszków 9D,1.0,0,118.23,1250000.0,osobaFizyczna,osobaFizyczna,wolnyRynek,pierwotny,1/1,2025-08-08,transakcja
229521,52.201158,20.907891,Ulica Solipska 27,6.0,0,65.60,875000.0,osobaFizyczna,osobaFizyczna,wolnyRynek,wtorny,1/1,2025-07-08,transakcja
229613,52.285877,21.170294,Ulica Mokry Ług 71D,1.0,0,66.82,600000.0,osobaFizyczna,osobaFizyczna,wolnyRynek,pierwotny,1/1,2025-02-20,transakcja
229614,52.285877,21.170294,Ulica Mokry Ług 71D,1.0,0,66.82,1035000.0,osobaFizyczna,osobaFizyczna,wolnyRynek,wtorny,1/1,2025-07-24,transakcja
229647,52.257368,21.163250,Ulica Cyrulików 63,3.0,0,25.30,295000.0,osobaFizyczna,osobaFizyczna,wolnyRynek,wtorny,1/1,2025-04-10,transakcja

In [53]:
data[data['rooms'] > 7]

,latitude,longitude,street,floor,rooms,size,amount,buyerType,sellerType,transactionType,marketType,participation,creation_date,classification
1560,52.201837,21.026557,Ulica Ludowa 17,7.0,8,177.50,2600000.00,osobaFizyczna,osobaFizyczna,wolnyRynek,wtorny,1/1,2019-02-05,transakcja
4054,52.332118,20.940414,Ulica Książkowa 9F,5.0,9,82.50,210000.00,osobaFizyczna,osobaFizyczna,wolnyRynek,wtorny,1/1,2017-11-16,transakcja
4773,52.155977,21.033450,Aleja Komisji Edukacji Narodowej 93,13.0,13,63.10,1200000.00,osobaFizyczna,osobaFizyczna,wolnyRynek,wtorny,1/1,2024-05-06,transakcja
5864,52.184539,20.992559,Ulica Konstruktorska 9A,9.0,9,27.34,600000.00,osobaFizyczna,osobaFizyczna,wolnyRynek,wtorny,1/1,2025-07-21,transakcja
9832,52.212137,20.971257,Ulica Białobrzeska 15,6.0,8,168.27,1500000.00,osobaFizyczna,osobaFizyczna,wolnyRynek,wtorny,1/1,2017-09-21,transakcja
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
228933,52.172577,21.116165,Ulica Gobelinowa 12,1.0,8,251.74,3750000.00,osobaFizyczna,osobaPrawna,wolnyRynek,pierwotny,1/1,2025-08-01,transakcja
228934,52.172577,21.116165,Ulica Gobelinowa 12,1.0,8,251.93,3800000.00,osobaFizyczna,osobaFizyczna,wolnyRynek,pierwotny,1/1,2025-08-23,transakcja
229086,52.297801,21.050600,Ulica Ostródzka 7A,1.0,9,125.91,1500000.00,osobaFizyczna,osobaPrawna,wolnyRynek,pierwotny,1/1,2025-05-05,transakcja
229127,52.176443,21.107634,Ulica Syta 150,1.0,8,185.15,2136510.00,osobaFizyczna,osobaPrawna,wolnyRynek,pierwotny,1/1,2025-09-23,transakcja
229392,52.154344,21.126655,Ulica Syta 26A,1.0,8,216.30,2441830.68,osobaFizyczna,osobaPrawna,wolnyRynek,pierwotny,1/1,2025-03-28,transakcja